FROM ogre0403/gemini:0.1.10-base

USER root


RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev \
    python3-openstackclient \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


USER node
CMD ["gemini"]

