ARG IMAGE=ogre0403/gemini
ARG VERSION=0.1.10
FROM ${IMAGE}:${VERSION}-base

USER root


RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev \
    python3-openstackclient \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


USER node
CMD ["gemini"]

