ARG IMAGE=ogre0403/gemini
ARG VERSION=0.1.10
FROM ${IMAGE}:${VERSION}-upstream

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/usr/local/bin" sh

USER node
CMD ["gemini"]

